# lifenode theme
# This theme is licensed under MIT license.
# See also LICENSE.txt for detail.

title: Lifenode
author: nukosuke
email: nukosuke@lavabit.com
description: >-
  lifenode is simple theme for Jekyll.

# URL settings
permalink: "/:year/:month/:day/:title:output_ext"

# build settings
markdown: kramdown
theme: lifenode
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore
  - vendor/
